Repository Mukesh-kanna/python-content-repo, pull requests merged in 2021-10, with the labels that each got.

#1 Created Readme
  README.md
Labels: invalid, spam

#2 ADDED hangman.py
  hangman.py
Labels: hacktoberfest-accepted

#3 Jbranch
  secretauc/art.py
  secretauc/main.py
Labels: Hacktoberfest, hacktoberfest-accepted

#4 Create openweatherapi.py
  openweatherapi.py
Labels: Hacktoberfest, hacktoberfest-accepted

#5 Create ccipher.py
  ccipher.py
Labels: Hacktoberfest, hacktoberfest-accepted

#7 Create guessnumber.py
  guessnumber.py
Labels: Hacktoberfest, hacktoberfest-accepted

#8 Create higher-lowergame.py
  higher-lowergame.py
Labels: Hacktoberfest, hacktoberfest-accepted

#11 Create travis.py
  travis.py
Labels: Hacktoberfest, hacktoberfest-accepted

#14 Create milkil.py
  milkil.py
Labels: Hacktoberfest, hacktoberfest-accepted

#19 Create sharpe_sortino.py
  sharpe_sortino.py
Labels: Hacktoberfest, hacktoberfest-accepted

#25 Create Qr-reader.py
  Qr-reader.py
Labels: Hacktoberfest, hacktoberfest-accepted

#12 Create travis.py
  travis.py
Labels: Hacktoberfest, hacktoberfest-accepted

#21 Create cagr.py
  cagr.py
Labels: Hacktoberfest, hacktoberfest-accepted

#22 Create f_stockrow.py
  f_stockrow.py
Labels: Hacktoberfest, hacktoberfest-accepted

#15 Create crudeoil.py
  crudeoil.py
Labels: Hacktoberfest, hacktoberfest-accepted

#16 Create rsis.py
  rsis.py
Labels: Hacktoberfest, hacktoberfest-accepted

#24 Create studmngmtsys.py
  studmngmtsys.py
Labels: Hacktoberfest, hacktoberfest-accepted

#23 Create multiple_Tickers_yahooof.py
  multiple_Tickers_yahooof.py
Labels: Hacktoberfest, hacktoberfest-accepted

#20 Create portfoliobalancing.py
  portfoliobalancing.py
Labels: Hacktoberfest, hacktoberfest-accepted

#18 Create fromula_stockgrowusa.py
  fromula_stockgrowusa.py
Labels: Hacktoberfest, hacktoberfest-accepted

#26 Create LeapYear.py
  LeapYear.py
Labels: Hacktoberfest, hacktoberfest-accepted

#28 Create primenumberidentifier.py
  primenumberidentifier.py
Labels: Hacktoberfest, hacktoberfest-accepted

#29 Create largestsmallestnumber.py
  largestsmallestnumber.py
Labels: Hacktoberfest, hacktoberfest-accepted
